name: Generate snake animation

on:
  schedule:
    - cron: "0 */24 * * *" 

  workflow_dispatch:
  
  push:
    branches:
    - main  
    
  

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - uses: actions/checkout@v3
        with:
          repository: Deoships/snk
          ref: main  
          path: snk
          
      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  

      - name: Install dependencies and build snk
        run: |
          cd snk
          npm install
          npm run build  # Or yarn build, if your fork uses yarn. Check your package.json

      - name: generate github-contribution-grid-snake.svg
        run: |
          cd snk
          node ./dist/cli.js --github_user_name ${{ github.repository_owner }} --output dist/github-contribution-grid-snake.svg dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          #  npm run snake -- --github_user_name ${{ github.repository_owner }} # Original line, might still work but using direct node call for more control

      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
