name: snake-github-profile

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'info'
        type: choice
        options:
          - info
          - debug

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Deoships
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg
          color_head: '#70a5fd'
          color_snake: '#70a5fd'
          color_dots: '#70a5fd,#426696,#264061,#192b48'
          show_progress_bar: false
      - name: push to github
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
